INSERT INTO SUPPLIER (ID, NAME) VALUES (100, 'ChipArt');
INSERT INTO SUPPLIER (ID, NAME) VALUES (200, 'Pichau');
INSERT INTO SUPPLIER (ID, NAME) VALUES (300, 'TerabyteShop');
INSERT INTO SUPPLIER (ID, NAME) VALUES (400, 'Kabum');

INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (100, 'Placa mãe');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (200, 'Fonte');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (300, 'Processadores');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (400, 'GPU');

INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY, CREATED_AT) VALUES (100, 'RTX 3060', 100, 400, 7, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY, CREATED_AT) VALUES (200, 'Ryzen 5 3600x', 200, 300, 12, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY, CREATED_AT) VALUES (300, 'Fonte coolermaster', 300, 200, 8, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY, CREATED_AT) VALUES (400, 'Asus a320', 400, 100, 9, CURRENT_TIMESTAMP);


